# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = "0.2.1.post1.dev45+g6a96295.d20221014"
__version_tuple__ = version_tuple = (0, 2, 1, "dev45", "g6a96295.d20221014")
