name: test docs build

on:
  pull_request:
    branches:
      - docs

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          channels: conda-forge
          channel-priority: strict
          activate-environment: sphinx-docs
          environment-file: ./docs/conda_env.yml
          use-only-tar-bz2: true
      - run: |
          conda activate sphinx-docs
          which pip

      - name: Install package
        run: python3 -m pip install .[mushin]

      - name: Install docs dependencies
        run: pip install -r ./docs/requirements.txt

      - name: Run sphinx
        run: (cd ./docs/ && make html)
